codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: 5ed548cd-073b-4748-b584-ca2d637027bf

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
