codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: d65de923-7c3d-4836-8d9a-5183b356be4f

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
